[build]
  command = "NODE_OPTIONS=--max-old-space-size=4096 npm run build"
  publish = "dist"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[plugins.inputs]
  thresholds = { performance = 0.9, accessibility = 0.9, best-practices = 0.9, seo = 0.9 }

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache"
