name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy every time you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Add CNAME and .nojekyll
        run: |
          echo 'baydarandbaydar.com' > dist/CNAME
          touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist